ARG GENERATE_SOURCEMAP
ARG PORT
ARG REACT_APP_HOST_API_KEY
ARG REACT_APP_MAPBOX_API
ARG REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ARG REACT_APP_FIREBASE_PROJECT_ID
ARG REACT_APP_FIREBASE_STORAGE_BUCKET
ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID
ARG REACT_APP_FIREBASE_APPID
ARG REACT_APP_FIREBASE_MEASUREMENT_ID
ARG REACT_APP_AWS_COGNITO_USER_POOL_ID
ARG REACT_APP_AWS_COGNITO_CLIENT_ID
ARG REACT_APP_AUTH0_DOMAIN
ARG REACT_APP_AUTH0_CLIENT_ID

FROM node:16 as build-deps
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn
COPY . ./
RUN yarn build

FROM nginx:1.12-alpine
COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
