FROM node:16 as build-deps

ARG GENERATE_SOURCEMAP
ARG PORT
ARG REACT_APP_HOST_API_KEY
ARG REACT_APP_MAPBOX_API
ARG REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ARG REACT_APP_FIREBASE_PROJECT_ID
ARG REACT_APP_FIREBASE_STORAGE_BUCKET
ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID
ARG REACT_APP_FIREBASE_APPID
ARG REACT_APP_FIREBASE_MEASUREMENT_ID
ARG REACT_APP_AWS_COGNITO_USER_POOL_ID
ARG REACT_APP_AWS_COGNITO_CLIENT_ID
ARG REACT_APP_AUTH0_DOMAIN
ARG REACT_APP_AUTH0_CLIENT_ID

RUN echo $REACT_APP_HOST_API_KEY

WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn global add serve
RUN yarn
COPY . ./
RUN yarn build

CMD ["serve", "-s", "build"]
